packages:
  - apps/*
  - packages/*
  - lib/*
onlyBuiltDependencies:
  - '@swc/core'
  - esbuild
  - simple-git-hooks
  - unrs-resolver
overrides:
  '@eslint-community/eslint-utils': ^4.7.0
  '@typescript-eslint/utils': ^8.32.1
  eslint: ^9.27.0
  tsx: ^4.19.4
