name: "🐛 Bug Report"
description: Create a new ticket for a bug.
title: "🐛 [BUG] - <title>"
labels:
  - bug
projects:
  - bjf5201/ts-configs
assignees: 
  - bjf5201
body:
  - type: markdown
    attributes:
      value: "# Bug Report"
  - type: checkboxes
    id: issue-check
    attributes:
      label: "0. Search Issues"
      description: "Please [search the repository](https://github.com/bjf5201/ts-configs/issues) to check if an issue for this bug already exists."
      options:
        - label: I have checked the repository for identical bug reports.
          required: true
  - type: markdown
    attributes:
      value: "## Problem Info"
  - type: textarea
    id: current-description
    attributes:
      label: 1. Current Behavior
      description: "Please enter a **thorough** description of your issue."
      placeholder: Concise and explicit description of your incident.
    validations:
      required: true
  - type: textarea
    id: expected-description
    attributes:
      label: 2. Expected Behavior
      description: "What did you expect to happen?"
      placeholder: 
    validations:
      required: true
  - type: textarea
    id: reprod
    attributes:
      label: 3. Reproduction Steps
      render: bash
      description: What steps led to your issue? Please enter the specific steps to reproduce it. (Don't worry about putting it into a codeblack/using backticks - the text will be automatically formatted into code).
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true
  - type: input
    id: reprod-url
    attributes:
      label: 4. Reproduction URL
      description: Please enter a URL that provides a reproduction of the issue, if applicable (i.e., https://codesandbox.io/p/sandbox/github/GH-USERNAME/GH-REPO-NAME or https://github.com/USERNAME/REPO-NAME).
      placeholder: i.e., https://github.com/USERNAME/REPO-NAME
    validations:
      required: false
  - type: textarea
    id: screenshot
    attributes:
      label: 5. Screenshots
      description: |
        If applicable, upload screenshots to help explain your problem.
        *Tip - You can attach images or log files by clicking this area to highlight it and then dragging files in.*
      placeholder: |
        ![DESCRIPTION](LINK.png)
      render: bash
    validations:
      required: false
  - type: markdown
    attributes:
      value: "## Environment"
  - type: dropdown
    id: app-version
    attributes:
      label: 6. ts-configs Version
      description: "What version of `ts-configs` are you using? You can run the command `ts-configs --version` or `ts-configs -v` to retrieve this information."
      options:
        - 0.1.0 (latest)
      default: 0
    validations:
      required: true
  - type: textarea
    attributes:
      label: 2. Relevant Systems & Apps
      description: |
        examples:
          - **OS**: Ubuntu 20.04
          - **Node**: 13.14.0
          - **Package Manager**: pnpm 10.9.0
          - **Eslint**: 9.27.0
          - **Prettier**: 3.5.3
      value: |
          - OS:
          - Node:
          - Package Manager:
          - Eslint:
          - Prettier:
      render: markdown
    validations:
      required: false
  - type: textarea
    id: logs
    attributes:
      label: 5. Logs / Relevant Output
      render: bash
      description: |
        If you have an error while developing library - Please run `git diagnose` and copy output here, in addition to any other relevent logs.
    
        **For all other bugs -** Please copy and paste any relevant logs and/or CLI output. (Again, this will be automatically formatted into code, so no need for backticks). 
    
        *Tip - You can attach log files by clicking this area to highlight it and then dragging files in.*
    validations:
      required: false
  - type: markdown
    attributes:
      value: "## Misc"
  - type: textarea
    attributes:
      label: 6. Anything else?
      description: |
        Additional links? References? Anything that will give more context about the issue you are encountering!
        *Tip - You can attach images or log files by clicking this area to highlight it and then dragging files in.*
    validations:
      required: false
  - type: checkboxes
    id: conduct
    attributes:
      label: 7. Code of Conduct
      description: By submitting this issue, you agree to follow ts-configs' [Code of Conduct](https://github.com/bjf5201/ts-configs/blob/main/.github/CODE_OF_CONDUCT).
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
