name: "💡 Feature Request"
description: Create a new ticket for a new feature request
title: "💡 [REQUEST] - <title>"
assignees: [
  "bjf5201"
]
labels: [
  "feat"
]
body:
  - type: markdown
    attributes:
      value: |
        # Feature Request

        Thank you for taking the time to fill out this feature request!

        Before filling out this request, please ensure that you have:
          - read the [contributing guide](https://github.com/bjf5201/ts-configs/.github/CONTRIBUTING.md)
          - read the [Code of Conduct](https://github.com/bjf5201/ts-configs/.github/blob/main/.github/CODE_OF_CONDUCT)
          - searched [the repository's issues](https://github.com/bjf5201/ts-configs/issues) to ensure this isn't a repeat request
  - type: checkboxes
    id: checklist
    attributes:
      label: Preliminary Steps
      description: Check off each action once complete. In case you missed it, you can find the [contributing guide here](https://github.com/bjf5201/ts-configs/.github/CONTRIBUTING.md), the [Code of Conduct here](https://github.com/bjf5201/ts-configs/blob/main/.github/CODE_OF_CONDUCT) and all the [repository's issues here](https://github.com/bjf5201/ts-configs/issues).
      options:
        - label: Have you searched the repository's issues to ensure this isn't a repeat request? (required)
          required: true
        - label: Have you read the contributing guide?
          required: true
        - label: Do you agree to abide by ts-configs' Code of Conduct?
          required: true
  - type: input
    id: start_date
    attributes:
      label: "Start Date"
      description: Start of development
      placeholder: "month/day/year"
    validations:
      required: false
  - type: textarea
    id: implementation_pr
    attributes:
      label: "Implementation PR"
      description: Pull request used
      placeholder: "#Pull Request ID"
    validations:
      required: false
  - type: textarea
    id: reference_issues
    attributes:
      label: "Reference Issues"
      description: Common issues
      placeholder: "#Issues IDs"
    validations:
      required: false
  - type: textarea
    id: summary
    attributes:
      label: "Summary"
      description: Provide a brief explanation of the feature
      placeholder: Describe in a few lines your feature request
    validations:
      required: true
  - type: textarea
    id: basic_example
    attributes:
      label: "Basic Example"
      description: Indicate here some basic examples of your feature.
      placeholder: A few specific words about your feature request or links to examples.
    validations:
      required: true
  - type: textarea
    id: drawbacks
    attributes:
      label: "Impacts"
      description: What are the drawbacks/impacts of your feature request ?
      placeholder: Identify the drawbacks and impacts while being neutral on your feature request
    validations:
      required: true
  - type: dropdown
    id: contribute
    attributes:
      label: Would you be willing to implement this feature?
      options:
        - Yes
        - Not right now!
    validations:
      required: true
    
